Style/RedundantReturn:
  Enabled: false

Style/PredicateName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/NotNil:
  Enabled: false

Lint/DebugCalls:
  Enabled: false

Documentation/DocumentationAdmonition:
  Enabled: false  